### ISSUE TITLE
Q: Will this work in the browser via pubsub?

### ISSUE THREAD

**Issue by aphelionz** [JoinColony/pinion#103]
Perhaps a wild question, but I'm definitely curious!

**Comment by rdig** [comment]
Not of out the box, no.

This was designed to be a standalone, node service, that would listen in a pubsub room and act on the various messages posted there.

In our usage scenario, the browser would join the pubsub room via the ipfs client, but would do no pinning itself.

I _think_ this can be adapted to work in the browser as well, although I suspect a bunch of concessions need to be made for that, which would render the pinner less useful

**Comment by chmanie** [comment]
Interesting thought. It would defy the purpose of it, of being always online but I think it _could_. There are almost no node dependencies (that can't be ponyfilled easily). We'd just need to build it via webpack or other means, supplying the configuration via env variables set at build time.

**Comment by aphelionz** [comment]
Cool! Thank you for the input. My curiousity is satisfied for now
